### ISSUE TITLE
GnuTLS format changed

### ISSUE THREAD

**Issue by janbrasna** [april/tls-table#8]
https://gitlab.com/gnutls/gnutls/-/blob/master/lib/algorithms/ciphersuites.c

Lines used to look like:

` #define GNUTLS_DH_ANON_3DES_EDE_CBC_SHA1 { 0x00, 0x1B }`

now it's multiline

```
#define GNUTLS_DH_ANON_3DES_EDE_CBC_SHA1 \
	{                                \
		0x00, 0x1B               \
	}
```

resulting in misparsing like:
```
  Warning: code point #defineGNUTLS_ECDHE_ECDSA_AES_128_CBC_SHA1\ (TLS_ECDHE_ECDSA_AES_128_CBC_SHA1) not in IANA registry
  Warning: code point #defineGNUTLS_ECDHE_ECDSA_AES_256_CBC_SHA1\ (TLS_ECDHE_ECDSA_AES_256_CBC_SHA1) not in IANA registry
```

**Comment by janbrasna** [comment]
Fortunately earlier this year that change got reverted in [1a5db76](https://gitlab.com/gnutls/gnutls/-/commit/1a5db76f8273ad5f40187583905ebc297edc1a0c#2e492f2fe1795fa96a4ec8295b2aab56cfd33d09_82_72) so the GnuTLS parsing should be working again!

_(Haven't tested yet, but happy to close if someone can confirm it working again…)_

**Comment by gstrauss** [comment]
Looks to me like it is working; no "not in IANA registry" warnings for these when I run the script.

**Comment by janbrasna** [comment]
It's not failing completely, but has a few kinks still:

```
Retrieving IANA cipher List
Retrieving NSS cipher list
  Warning: code point 0x00,0x66 (TLS_DHE_DSS_WITH_RC4_128_SHA) not in IANA registry
  Warning: code point 0x00,0x62 (TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA) not in IANA registry
  Warning: code point 0x00,0x64 (TLS_RSA_EXPORT1024_WITH_RC4_56_SHA) not in IANA registry
  Warning: code point 0x00,0x63 (TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA) not in IANA registry
  Warning: code point 0x00,0x65 (TLS_DHE_DSS_EXPORT1024_WITH_RC4_56_SHA) not in IANA registry
Retrieving OpenSSL cipher list
Retrieving GnuTLS cipher list
  Warning: code point #defineGNUTLS_SSL3GNUTLS_TLS1 (TLS_SSL3) not in IANA registry
  Warning: code point 0x00,0x66 (TLS_DHE_DSS_ARCFOUR_128_SHA1) not in IANA registry
  Warning: code point 0xc1,0x02 (TLS_GOSTR341112_256_28147_CNT_IMIT) not in IANA registry
```

(I'm mostly aiming at the #define being misparsed. None of these are present with #10 though.)
